fixed some makefile issues

diff --git a/microbenchmarks/concrete/cksum/Makefile b/microbenchmarks/concrete/cksum/Makefile
--- a/microbenchmarks/concrete/cksum/Makefile
+++ b/microbenchmarks/concrete/cksum/Makefile
@@ -6,18 +6,11 @@ all: build/main build/obj.dump
 
 
 build/main:
-	docker run --user $$(id -u):$$(id -g) --rm -it --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
+	docker run --user $$(id -u):$$(id -g) --rm --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
 
 
 test:
 	cd build/ && rm -f Monitor* && cp ../GutenburgDictionary.txt . && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false
-
-
-smalltest:
-	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false - ../harness.c
-
-smallmixedtest:
-	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -singleStepping -check-overshift=false - ../harness.c
 
 mixedtest:
 	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -singleStepping -check-overshift=false  - ../harness.c
@@ -26,11 +19,46 @@ build/obj.dump: build/main
 	objdump -C -D -w -M suffix -j .text build/main > build/obj.dump
 
 clean:
-	rm -rf build/*
+	rm -rf build/* res*.txt interpres*.txt mixedres*.txt
 
 
-mixedres:
-	grep harness build/Monitor | tail -n1 > mixedres.txt
 
-interpres:
-	grep harness build/Monitor | tail -n1 > interpres.txt
+
+build/Monitor.interp%:
+	cd build/ && ./run.sh -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - ../harness.c
+
+build/Monitor.mixed%:
+	cd build/ && ./run.sh -dontFork -taseManager=false -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - ../harness.c
+
+ref.txt:
+	cd build/ && cksum ../harness.c > ../ref.txt
+
+
+mixedres%.txt: build/Monitor.mixed%
+	grep harness $< | tail -n1 > $@
+
+interpres%.txt: build/Monitor.interp% 
+	grep harness $< | tail -n1 > $@
+
+
+.PHONY: resx5.txt
+resx5.txt: cleanres res_1.txt res_2.txt res_3.txt res_4.txt res_5.txt
+	echo "cksum:" > resx5.txt
+	cat res_*.txt >> resx5.txt
+
+.PHONY: res.txt
+res.txt: cleanres res_1.txt
+	echo "cksum:" > res.txt
+	cat res_1.txt >> res.txt
+
+
+.PHONY: cleanres
+cleanres:
+	rm -f res_*.txt mixedres*.txt interpres*.txt Monitor.mixed* Monitor.interp*
+
+
+
+res_%.txt: ref.txt mixedres%.txt interpres%.txt
+	echo "  rep$*:" >> $@
+	diff -q ref.txt interpres$*.txt &>/dev/null; x=$$?; if [ $$x -ne 0 ]; then echo "    interp: FAIL"; else echo "    interp: PASS"; fi >> $@
+	diff -q ref.txt mixedres$*.txt &>/dev/null; y=$$?; if [ $$y -ne 0 ]; then echo "    mixed: FAIL"; else echo "    mixed: PASS"; fi >> $@
diff --git a/microbenchmarks/concrete/factor/Makefile b/microbenchmarks/concrete/factor/Makefile
--- a/microbenchmarks/concrete/factor/Makefile
+++ b/microbenchmarks/concrete/factor/Makefile
@@ -8,7 +8,7 @@ all: build/main build/obj.dump
 
 
 build/main: 
-	docker run --user $$(id -u):$$(id -g) --rm -it --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
+	docker run --user $$(id -u):$$(id -g) --rm --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
 
 .PHONY: test gdbtest smalltest mixedtest objdump clean
 test:
@@ -17,13 +17,6 @@ test:
 
 gdbtest:
 	cd build/ && env KLEE_RUNTIME_LIBRARY_PATH=$$(pwd)/bitcode/ gdb --args main -project=main -taseDebug -modelDebug -dontFork -taseManager=false -singleStepping -check-overshift=false - $(SMALL)
-
-
-smalltest:
-	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false - $(SMALL)
-
-smallmixedtest:
-	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -singleStepping -check-overshift=false - $(SMALL)
 
 mixedtest:
 	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -singleStepping -check-overshift=false - $(LARGE)
@@ -35,11 +28,46 @@ longtest:
 	cd build/ && rm -f Monitor* && nohup ./run.sh -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false - $(LARGE) &
 
 clean:
-	rm -rf build/*
+	rm -rf build/* res*.txt interpres*.txt mixedres*.txt
 
 
-mixedres:
-	grep $(SMALL) build/Monitor | tail -n1 | sed 's/.*"//g' > mixedres.txt
 
-interpres:
-	grep $(SMALL) build/Monitor | tail -n1 | sed 's/.*"//g' > interpres.txt
+.PRECIOUS: build/Monitor.interp% build/Monitor.mixed%
+build/Monitor.interp%:
+	cd build/ && ./run.sh -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - $(SMALL)
+
+
+build/Monitor.mixed%:
+	cd build/ && ./run.sh -dontFork -taseManager=false -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - $(SMALL)
+
+
+mixedres%.txt: build/Monitor.mixed%
+	grep $(SMALL) $< | tail -n1 | sed 's/.*"//g' > $@
+
+
+interpres%.txt: build/Monitor.interp%
+	grep $(SMALL) $< | tail -n1 | sed 's/.*"//g' > $@
+
+
+ref.txt:
+	factor $(SMALL) > ref.txt
+
+.PHONY: resx5.txt
+resx5.txt: cleanres res_1.txt res_2.txt res_3.txt res_4.txt res_5.txt
+	echo "factor:" > resx5.txt
+	cat $(wildcard res_*.txt) >> resx5.txt
+
+.PHONY: res.txt
+res.txt: cleanres res_1.txt
+	echo "factor:" > res.txt
+	cat $(wildcard res_*.txt) >> res.txt
+
+.PHONY: cleanres
+cleanres:
+	rm -f res*.txt
+
+
+res_%.txt: ref.txt mixedres%.txt interpres%.txt
+	echo "  rep$*:" >> $@
+	diff -q ref.txt interpres$*.txt; x=$$?; if [ $$x -ne 0 ]; then echo "    interp: FAIL"; else echo "    interp: PASS"; fi >> $@
+	diff -q ref.txt mixedres$*.txt; y=$$?; if [ $$y -ne 0 ]; then echo "    mixed: FAIL"; else echo "    mixed: PASS"; fi >> $@
diff --git a/microbenchmarks/concrete/md5sum/Makefile b/microbenchmarks/concrete/md5sum/Makefile
--- a/microbenchmarks/concrete/md5sum/Makefile
+++ b/microbenchmarks/concrete/md5sum/Makefile
@@ -6,17 +6,10 @@ all: build/main build/obj.dump
 
 
 build/main: 
-	docker run --user $$(id -u):$$(id -g) --rm -it --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
+	docker run --user $$(id -u):$$(id -g) --rm --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
 
 test:
 	cd build/ && rm -f Monitor* && cp ../GutenburgDictionary.txt . && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false
-
-
-smalltest:
-	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -execMode=INTERP_ONLY  -singleStepping -check-overshift=false - ../harness.c
-
-smallmixedtest:
-	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -singleStepping -check-overshift=false - ../harness.c
 
 
 mixedtest:
@@ -26,10 +19,42 @@ build/obj.dump: build/main
 	objdump -C -D -w -M suffix -j .text build/main > build/obj.dump
 
 clean:
-	rm -rf build/*
+	rm -rf build/* res*.txt interpres*.txt mixedres*.txt
 
-mixedres:
-	grep -A2 printf build/Monitor | tail -n1 > mixedres.txt
 
-interpres:
-	grep -A2 printf build/Monitor | tail -n1 > interpres.txt
+build/Monitor.interp%:
+	cd build/ && ./run.sh -dontFork -taseManager=false -execMode=INTERP_ONLY  -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - ../harness.c
+
+build/Monitor.mixed%:
+	cd build/ && ./run.sh -dontFork -taseManager=false -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - ../harness.c
+
+
+mixedres%.txt: build/Monitor.mixed%
+	x=$$(grep -c model_printf $<); if [ $$x -gt 0 ]; then grep -A2 _printf $< | tail -n1 > $@; else grep -A1 _puts $< | tail -n1 > $@; fi
+
+interpres%.txt: build/Monitor.interp%
+	x=$$(grep -c model_printf $<); if [ $$x -gt 0 ]; then grep -A2 _printf $< | tail -n1 > $@; else grep -A1 _puts $< | tail -n1 > $@; fi
+
+ref.txt:
+	cd build/ && md5sum ../harness.c | awk '{print $$1}' > ../ref.txt
+
+.PHONY: resx5.txt
+resx5.txt: cleanres res_1.txt res_2.txt res_3.txt res_4.txt res_5.txt
+	echo "md5sum:" > resx5.txt
+	cat res_*.txt >> resx5.txt
+
+.PHONY: res.txt
+res.txt: cleanres res_1.txt
+	echo "md5sum:" > res.txt
+	cat res_*.txt >> res.txt
+
+.PHONY: cleanres
+cleanres:
+	rm -f res*.txt
+
+
+
+res_%.txt: ref.txt interpres%.txt mixedres%.txt
+	echo "  rep$*:" >> $@
+	diff -q ref.txt interpres$*.txt; x=$$?; if [ $$x -ne 0 ]; then echo "    interp: FAIL"; else echo "    interp: PASS"; fi >> $@
+	diff -q ref.txt mixedres$*.txt; y=$$?; if [ $$y -ne 0 ]; then echo "    mixed: FAIL"; else echo "    mixed: PASS"; fi >> $@
diff --git a/microbenchmarks/concrete/tsort/Makefile b/microbenchmarks/concrete/tsort/Makefile
--- a/microbenchmarks/concrete/tsort/Makefile
+++ b/microbenchmarks/concrete/tsort/Makefile
@@ -6,7 +6,7 @@ all: build/main build/obj.dump
 
 
 build/main: 
-	docker run --user $$(id -u):$$(id -g) --rm -it --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
+	docker run --user $$(id -u):$$(id -g) --rm --mount type=bind,src=$$(pwd),dst=/project/ tase bash -c 'cd $(ROOT) && make CFLAGS="$(CFLAGS)" -f build.Makefile'
 
 
 test:
@@ -16,27 +16,54 @@ test:
 gdbtest: tsortShort
 	cd build/ && head -n 1000 ../tsortFile > tsortShort && env KLEE_RUNTIME_LIBRARY_PATH=$$(pwd)/bitcode/ gdb --args main -project=main -taseDebug -modelDebug -dontFork -taseManager=false -singleStepping -check-overshift=false - tsortShort
 
-smalltest: tsortShort
-	cd build/ && rm -f Monitor* && ./run.sh -modelDebug -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false - ../tsortShort
-
-smallmixedtest: tsortShort
-	cd build/ && rm -f Monitor* && ./run.sh -modelDebug -dontFork -taseManager=false  -singleStepping -check-overshift=false - ../tsortShort
-
 mixedtest:
-	cd build/ && rm -f Monitor* && ./run.sh -taseDebug -modelDebug -dontFork -taseManager=false -check-overshift=false -singleStepping -check-overshift=false - ../tsortFile
+	cd build/ && rm -f Monitor* && ./run.sh -dontFork -taseManager=false -check-overshift=false -singleStepping -check-overshift=false - ../tsortFile
 
 build/obj.dump: build/main
 	objdump -C -D -w -M suffix -j .text build/main > build/obj.dump
 
 clean:
-	rm -rf build/*
+	rm -rf build/* res*.txt interpres*.txt mixedres*.txt
 
-interpres:
-	grep ^OUT build/Monitor | awk '{print $$2}' > interpres.txt
 
-mixedres:
-	grep ^OUT build/Monitor | awk '{print $$2}' > mixedres.txt
+build/Monitor.interp%: tsortShort
+	cd build/ && ./run.sh -dontFork -taseManager=false -execMode=INTERP_ONLY -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - ../tsortShort
+
+
+build/Monitor.mixed%: tsortShort
+	cd build/ && ./run.sh -dontFork -taseManager=false  -singleStepping -check-overshift=false -modelDebug -log=$(notdir $@) - ../tsortShort
+
+
+interpres%.txt: build/Monitor.interp%
+	grep ^OUT $< | awk '{print $$2}' > $@
+
+mixedres%.txt: build/Monitor.mixed%
+	grep ^OUT $< | awk '{print $$2}' > $@
 
 
 tsortShort:
 	head -n 10000 tsortFile > tsortShort
+
+
+ref.txt: tsortShort
+	tsort tsortShort > ref.txt
+
+.PHONY: resx5.txt
+resx5.txt: cleanres res_1.txt res_2.txt res_3.txt res_4.txt res_5.txt
+	echo "tsort:" > resx5.txt
+	cat res_*.txt >> resx5.txt
+
+.PHONY: res.txt
+res.txt: cleanres res_1.txt
+	echo "tsort:" > res.txt
+	cat res_*.txt >> res.txt
+
+.PHONY: cleanres
+cleanres:
+	rm -f res*.txt
+
+
+res_%.txt: ref.txt interpres%.txt mixedres%.txt
+	echo "  rep$*:" >> $@
+	diff -q ref.txt interpres$*.txt &>/dev/null; x=$$?; if [ $$x -ne 0 ]; then echo "    interp: FAIL"; else echo "    interp: PASS"; fi >> $@
+	diff -q ref.txt mixedres$*.txt &>/dev/null; y=$$?; if [ $$y -ne 0 ]; then echo "    mixed: FAIL"; else echo "    mixed: PASS"; fi >> $@
